const header = {
  // all the properties are optional - can be left empty or deleted
  homepage: 'https://rajshekhar26.github.io/cleanfolio',
  title: 'BM.',
}

const about = {
  // all the properties are optional - can be left empty or deleted
  name: 'Basat Maqsood',
  role: 'Front End Developer',
  description:
    'I am a Software Engineer and a Front End Developer with experience in building web applications using React JS, Next JS, and Node JS according to the Principles of Software Engineering. I am passionate about building scalable and responsive web applications that provide a seamless user experience.',
  resume: 'https://example.com',
  social: {
    linkedin: 'https://linkedin.com/in/basatmaqsood',
    github: 'https://github.com/basatmaqsood',
  },
}

const projects = [
  // projects can be added an removed
  // if there are no projects, Projects section won't show up
  {
    name: 'Full Stack AirBnb Clone',
    description:
      'A Full Stack AirBnb Clone using Next JS, Tailwind CSS and Firebase. A simple interface in which user can search for different locations and see the available rooms. User can book a room and see the booking details.',
    stack: ['MERN Stack', 'Tailwind CSS', 'React JS','Express JS','MongoDB'],
    sourceCode: 'https://github.com/basatmaqsood/airbnb',
    // livePreview: 'https://github.com',
  },
  {
    name: 'Chat Application',
    description:
      'A working Chat Application in React JS with backend in Firebase. A simple interface in which user can search for other users. User can create a chat and send and receive messages from other users.',
    stack: ['React JS', 'Tailwind CSS', 'Firebase'],
    sourceCode: 'https://github.com/basatmaqsood/chatapp',
    // livePreview: 'https://github.com',
  },
  {
    name: 'Chat GPT Clone',
    description:
      'A working Chat Application in React JS with backend in COHERE-AI integration. A simple interface in which user can enter a prompt and the response will be generated by Cohere AI and displayed on the page.',
    stack: ['React JS', 'Cohere AI API', 'CSS'],
    sourceCode: 'https://github.com/basatmaqsood/chatgpt',
    // livePreview: 'https://github.com',
  },
  {
    name: 'Wordle Clone',
    description:
      'A clone of famous Wordle game using React JS. It\'s a word guessing game with different colors for correct, incorrect and wrongly placed letters.I have also an on-screen keyboard for typing the letters.',
    stack: ['React JS', 'CSS'],
    sourceCode: 'https://github.com/basatmaqsood/wordle',
    // livePreview: 'https://github.com',
  },
  {
    name: 'Data Analytics',
    description:
    'A Simple and Responsive UI design for a data analytics company named "Growth" using React JS and Tailwind CSS. A single page web application design with different sections for Resources, About and Contact form.',
    stack: ['React JS', 'Tailwind CSS'],
    sourceCode: 'https://github.com/basatmaqsood/growth',
    // livePreview: 'https://github.com',
  },
  {
    name: 'Social Media App',
    description:
      'A simple and Responsive UI design for a social media app using React JS and Material UI. Show posts by the users and add reactions to each post. A left sidebar for menu and right sidebar for messages section.',
    stack: ['React JS', 'Material UI', 'Tailwind CSS'],
    sourceCode: 'https://github.com/basatmaqsood/material-UI',
    // livePreview: 'https://github.com',
  },
  {
    name: 'Other Projects',
    description:
      'A number of projects developed using HTML CSS and JavaScript including a car rental websites, a coffee website, a calculator and A tour website. All the projects are responsive and available on my GitHub profile.',
    stack: ['HTML', 'CSS', 'JavaScript'],
    sourceCode: 'https://github.com/basatmaqsood/',
    // livePreview: 'https://github.com',
  },
]

const skills = [
  // skills can be added or removed
  // if there are no skills, Skills section won't show up
  'HTML',
  'CSS',
  'JavaScript',
  'React JS',
  'Next JS',
  'Node JS',
  'Redux',
  'Material UI',
  'Git',
  'Java',
  'JavaFX',
  'Oracle SQL',
  'C++'
]

const contact = {
  // email is optional - if left empty Contact section won't show up
  email: 'itzbasatmaqsood@mail.com',
}

export { header, about, projects, skills, contact }
